# Generated by Django 5.2.6 on 2025-09-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=125)),
                ('lastname', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=125)),
                ('mobile', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Princess'), ('O', 'Other')], max_length=1)),
                ('about', models.TextField(max_length=125)),
                ('date', models.DateField()),
            ],
        ),
    ]
